#!/bin/bash

export $(grep -v '^#' ./supabase/.env | xargs)

supabase secrets set \
  PROJECT_URL=$PROJECT_URL \
  ANON_KEY=$ANON_KEY \
  OPENAI_API_KEY=$OPENAI_API_KEY \
  GEMINI_API_KEY=$GEMINI_API_KEY \
  AUTH_EXTERNAL_GOOGLE_ENABLED=$AUTH_EXTERNAL_GOOGLE_ENABLED \
  AUTH_EXTERNAL_GOOGLE_CLIENT_ID=$AUTH_EXTERNAL_GOOGLE_CLIENT_ID \
  AUTH_EXTERNAL_GOOGLE_SECRET=$AUTH_EXTERNAL_GOOGLE_SECRET

supabase functions deploy image-generator